// Build script for `aionui-opencode-conformance`.
//
// Reads the single source-of-truth SDK version from
// `../../../opencode-sdk-version.json` (relative to `CARGO_MANIFEST_DIR`,
// i.e. `<chisl-root>/opencode-sdk-version.json`) and emits a small
// `version.rs` into cargo's `OUT_DIR` that the library re-includes as
// `OPENCODE_SDK_VERSION` and friends.
//
// This is the canonical Rust-side reference; the JS-side sync script
// (`AionUi/scripts/sync-opencode-types.js`) reads the same JSON file and
// fails fast when the installed `@opencode-ai/sdk` doesn't match.
//
// Rerun triggers:
//   - the version JSON itself changes
//   - this build.rs changes
// Any other source change in the crate does NOT retrigger the version read,
// which keeps `cargo check` cheap.

use std::env;
use std::fs;
use std::path::PathBuf;

const VERSION_FILE_RELATIVE_FROM_MANIFEST: &str = "../../../opencode-sdk-version.json";
const OUT_FILE: &str = "version.rs";

fn main() {
    println!("cargo:rerun-if-changed={}", VERSION_FILE_RELATIVE_FROM_MANIFEST);
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let version_path = manifest_dir.join(VERSION_FILE_RELATIVE_FROM_MANIFEST);

    let raw = match fs::read_to_string(&version_path) {
        Ok(s) => s,
        Err(err) => {
            // Hard-fail the build with a precise message. This crate is a
            // contract gate; it must never silently fall back to a hardcoded
            // version, or the Rust/TS drift problem the SoT file exists to
            // prevent is back.
            panic!(
                "aionui-opencode-conformance: cannot read SDK version file at {}\n\
                 ({})\n\
                 This crate is gated on the chisl-root opencode-sdk-version.json — create it\n\
                 (or fix the path) before building. See AionCore/crates/aionui-opencode-conformance/README.md.",
                version_path.display(),
                err,
            );
        }
    };

    let parsed: serde_json::Value = match serde_json::from_str(&raw) {
        Ok(v) => v,
        Err(err) => {
            panic!(
                "aionui-opencode-conformance: opencode-sdk-version.json at {} is not valid JSON: {}",
                version_path.display(),
                err
            );
        }
    };

    let pkg = parsed
        .get("package")
        .and_then(|v| v.as_str())
        .unwrap_or("@opencode-ai/sdk");
    let version = parsed
        .get("version")
        .and_then(|v| v.as_str())
        .expect("opencode-sdk-version.json is missing required `version` field");
    let binary = parsed.get("binary").and_then(|v| v.as_str()).unwrap_or("");
    let last_verified = parsed.get("lastVerified").and_then(|v| v.as_str()).unwrap_or("");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("cargo sets OUT_DIR for build scripts"));
    let out_path = out_dir.join(OUT_FILE);
    let body = format!(
        "// AUTO-GENERATED by build.rs — DO NOT EDIT.\n\
         //\n\
         // Source: <chisl-root>/opencode-sdk-version.json\n\
         // Regenerate by touching that file; cargo will rerun this build script.\n\
         //\n\
         // These constants are the Rust-side mirror of the JS sync script's\n\
         // pin check. If you bump `version` in the JSON, you must also bump\n\
         // `AionUi/package.json` devDependencies.\"@opencode-ai/sdk\" (and\n\
         // re-run `bun run types:sync-opencode`) — otherwise the two repos\n\
         // drift and PROTOCOL.md stops describing reality.\n\
         \n\
         /// The exact `@opencode-ai/sdk` package name this crate is pinned against.\n\
         pub const OPENCODE_SDK_PACKAGE: &str = {pkg:?};\n\
         \n\
         /// The exact `@opencode-ai/sdk` semver version this crate is pinned\n\
         /// against. Mirrors `opencode-sdk-version.json::version` and the\n\
         /// `devDependencies.\"@opencode-ai/sdk\"` entry in AionUi/package.json.\n\
         pub const OPENCODE_SDK_VERSION: &str = {version:?};\n\
         \n\
         /// The exact `opencode serve` binary version the live capture in the\n\
         /// fixtures/ directory was taken against. Independent of the SDK\n\
         /// version because npm SDK and the CLI ship on independent cadences.\n\
         pub const OPENCODE_BINARY_VERSION: &str = {binary:?};\n\
         \n\
         /// ISO-8601 date the JSON pin was last touched.\n\
         pub const OPENCODE_SDK_PIN_LAST_VERIFIED: &str = {last_verified:?};\n",
    );

    if let Err(err) = fs::write(&out_path, body) {
        panic!(
            "aionui-opencode-conformance: failed to write {}: {}",
            out_path.display(),
            err
        );
    }
}
